### ISSUE TITLE
Routes (URL scheme)

### ISSUE THREAD

**Issue by hidehiro98** [hidehiro98/airflow_beta#4]
Using created_requests_controller and received_reqeusts_controller

URL example with sub domain (we implement later)
team_name.airflow.com/requests

**Comment by db0sch** [comment]
Why don't you use the routes generator, such as:
`resources :requests`
it will create automatically the routes... better, and more maintainable.

**Comment by hidehiro98** [comment]
I think we need requests_controller because for individual requests, the URL of individual requests should be `/request/1`.
How do you think about it?

**Comment by db0sch** [comment]
Yes! You are right.
So, you would need something like this:
`created_requests_controller`
with method: `index`
same for `received_requests_controller` (only method `index`)

And a `requests_controller` with the methods: `show`, `create`, `edit`, `update`... etc

**Comment by db0sch** [comment]
have a look at this article : http://jeromedalbert.com/how-dhh-organizes-his-rails-controllers/
this is how DHH write controller.

maybe you can organise your code like this:
`/controllers/requests_controller.rb`
`/controllers/requests/sent_controller.rb` or something like that.
`/controllers/requests/received_controller.rb` or something like that.

Article in Japanese http://postd.cc/how-dhh-organizes-his-rails-controllers/

**Comment by hidehiro98** [comment]
Can we nest the controllers? Amazing!

**Comment by hidehiro98** [comment]
We have 2 ways to organize controllers

1. DHH way (and our current way)
```
/controllers/requests_controller.rb
/controllers/requests/sent_requests_controller.rb
/controllers/requests/received_requests_controller.rb
```
```
routes.rb
  resources :requests, except: [:index]

  namespace :requests do
    resources :sent_requests, :received_requests, only: :index
  end
```

2. simple? way
```
/controllers/requests_controller.rb
```
```
routes.rb
  resources :requests do
    get 'sent', on: :collection
    get 'received', on: :collection
  end
```

**Comment by db0sch** [comment]
I think dedicated controller are better. You just do crud actions.
So first solution for me.

Dimitri Bosch
E-mail : dimitribosch@gmail.com

________________________________
