### ISSUE TITLE
Status list of request

### ISSUE THREAD

**Issue by hidehiro98** [hidehiro98/airflow_beta#5]
individual receiver
- pending: 0
- accepted: 1
- rejected: 2
- commented: 3

request
- pending: 0 (default status)
- accepted: 1 (all receiver accepted)
- rejected: 2 (at least one receiver rejected)
- commented: 3 (at least one receiver rejected) -> rejected ?

**Comment by db0sch** [comment]
for statuses, you can use Enums : http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html

**Comment by db0sch** [comment]
so "remand" is asking for more details or modification?

is this word the best? sounds like a legal word.

maybe you should ask an english speaker (Chris? Sam?) to check if the word is the correct one?

**Comment by hidehiro98** [comment]
Yes, "remand" is like that meaning.
I will ask Doug about the word.

**Comment by hidehiro98** [comment]
Doug gave me the 4 choices, and I think Unsettled is the best.
- Pending
- Awaiting
- Modify
- Unsettled

**Comment by db0sch** [comment]
But who is clicking on unsettled?
the reciever ? for what ? to ask new modification?
if so, I'll just use the word "Comment"

**Comment by hidehiro98** [comment]
I see, so "Comment" for button and "commented" for status in DB

**Comment by db0sch** [comment]
Yes. :ok:
